// ************************** Archers consts **************************
const int ARCHERS_HIT_AMOUNT = 5;
const int ARCHERS_WALK_AMOUNT = 8;

const int ARCHERS_HIT_DOWN_START_X = 0;
const int ARCHERS_HIT_DOWN_START_Y = 15;
const int ARCHERS_HIT_DOWN_ALL_WIDTH = 632;
const int ARCHERS_HIT_DOWN_WIDTH = ARCHERS_HIT_DOWN_ALL_WIDTH / ARCHERS_HIT_AMOUNT;
const int ARCHERS_HIT_DOWN_HEIGHT = 115;
const int ARCHERS_HIT_DOWN_END_X = 504;

const int ARCHERS_HIT_RIGHT_START_X = 0;
const int ARCHERS_HIT_RIGHT_START_Y = 173;
const int ARCHERS_HIT_RIGHT_ALL_WIDTH = 650;
const int ARCHERS_HIT_RIGHT_WIDTH = ARCHERS_HIT_DOWN_ALL_WIDTH / ARCHERS_HIT_AMOUNT;
const int ARCHERS_HIT_RIGHT_HEIGHT = 82;
const int ARCHERS_HIT_RIGHT_END_X = 504;

const int ARCHERS_HIT_UP_RIGHT_START_X = 0;
const int ARCHERS_HIT_UP_RIGHT_START_Y = 300;
const int ARCHERS_HIT_UP_RIGHT_ALL_WIDTH = 660;
const int ARCHERS_HIT_UP_RIGHT_WIDTH = ARCHERS_HIT_DOWN_ALL_WIDTH / ARCHERS_HIT_AMOUNT;
const int ARCHERS_HIT_UP_RIGHT_HEIGHT = 96;
const int ARCHERS_HIT_UP_RIGHT_END_X = 504;

const int ARCHERS_HIT_DOWN_RIGHT_START_X = 0;
const int ARCHERS_HIT_DOWN_RIGHT_START_Y = 431;
const int ARCHERS_HIT_DOWN_RIGHT_ALL_WIDTH = 644;
const int ARCHERS_HIT_DOWN_RIGHT_WIDTH = ARCHERS_HIT_DOWN_ALL_WIDTH / ARCHERS_HIT_AMOUNT;
const int ARCHERS_HIT_DOWN_RIGHT_HEIGHT = 99;
const int ARCHERS_HIT_DOWN_RIGHT_END_X = 504;

const int ARCHERS_HIT_UP_START_X = 0;
const int ARCHERS_HIT_UP_START_Y = 555;
const int ARCHERS_HIT_UP_ALL_WIDTH = 650;
const int ARCHERS_HIT_UP_WIDTH = ARCHERS_HIT_DOWN_ALL_WIDTH / ARCHERS_HIT_AMOUNT;
const int ARCHERS_HIT_UP_HEIGHT = 114;
const int ARCHERS_HIT_UP_END_X = 504;

const int ARCHERS_WALK_DOWN_RIGHT_START_X = 0;
const int ARCHERS_WALK_DOWN_RIGHT_START_Y = 689;
const int ARCHERS_WALK_DOWN_RIGHT_ALL_WIDTH = 1038;
const int ARCHERS_WALK_DOWN_RIGHT_WIDTH = ARCHERS_WALK_DOWN_RIGHT_ALL_WIDTH / ARCHERS_WALK_AMOUNT;
const int ARCHERS_WALK_DOWN_RIGHT_HEIGHT = 111;
const int ARCHERS_WALK_DOWN_RIGHT_END_X = 903;

const int ARCHERS_WALK_UP_START_X = 0;
const int ARCHERS_WALK_UP_START_Y = 817;
const int ARCHERS_WALK_UP_ALL_WIDTH = 1038;
const int ARCHERS_WALK_UP_WIDTH = ARCHERS_WALK_UP_ALL_WIDTH / ARCHERS_WALK_AMOUNT;
const int ARCHERS_WALK_UP_HEIGHT = 125;
const int ARCHERS_WALK_UP_END_X = 903;

const int ARCHERS_WALK_DOWN_START_X = 0;
const int ARCHERS_WALK_DOWN_START_Y = 958;
const int ARCHERS_WALK_DOWN_ALL_WIDTH = 1038;
const int ARCHERS_WALK_DOWN_WIDTH = ARCHERS_WALK_DOWN_ALL_WIDTH / ARCHERS_WALK_AMOUNT;
const int ARCHERS_WALK_DOWN_HEIGHT = 113;
const int ARCHERS_WALK_DOWN_END_X = 903;

const int ARCHERS_WALK_RIGHT_START_X = 0;
const int ARCHERS_WALK_RIGHT_START_Y = 1098;
const int ARCHERS_WALK_RIGHT_ALL_WIDTH = 1038;
const int ARCHERS_WALK_RIGHT_WIDTH = ARCHERS_WALK_RIGHT_ALL_WIDTH / ARCHERS_WALK_AMOUNT;
const int ARCHERS_WALK_RIGHT_HEIGHT = 100;
const int ARCHERS_WALK_RIGHT_END_X = 903;

const int ARCHERS_WALK_UP_RIGHT_START_X = 0;
const int ARCHERS_WALK_UP_RIGHT_START_Y = 1215;
const int ARCHERS_WALK_UP_RIGHT_ALL_WIDTH = 1038;
const int ARCHERS_WALK_UP_RIGHT_WIDTH = ARCHERS_WALK_UP_RIGHT_ALL_WIDTH / ARCHERS_WALK_AMOUNT;
const int ARCHERS_WALK_UP_RIGHT_HEIGHT = 134;
const int ARCHERS_WALK_UP_RIGHT_END_X = 903;


// ************************** Giant consts **************************
const int GIANT_HIT_AMOUNT = 8;
const int GIANT_WALK_AMOUNT = 8;

//hit down - right details :
const int GIANT_HIT_DOWN_RIGHT_START_X = 0;
const int GIANT_HIT_DOWN_RIGHT_START_Y = 42;
const int GIANT_HIT_DOWN_RIGHT_ALL_WIDTH = 1591;
const int GIANT_HIT_DOWN_RIGHT_WIDTH = GIANT_HIT_DOWN_RIGHT_ALL_WIDTH / GIANT_HIT_AMOUNT;
const int GIANT_HIT_DOWN_RIGHT_HEIGHT = 180;
const int GIANT_HIT_DOWN_RIGHT_END_X = 1386;

//hit up details :
const int GIANT_HIT_UP_START_X = 0;
const int GIANT_HIT_UP_START_Y = 214;
const int GIANT_HIT_UP_ALL_WIDTH = 1578;
const int GIANT_HIT_UP_WIDTH = GIANT_HIT_UP_ALL_WIDTH / GIANT_HIT_AMOUNT;
const int GIANT_HIT_UP_HEIGHT = 151;
const int GIANT_HIT_UP_END_X = 1379;

//hit down details :
const int GIANT_HIT_DOWN_START_X = 0;
const int GIANT_HIT_DOWN_START_Y = 456;
const int GIANT_HIT_DOWN_ALL_WIDTH = 1573;
const int GIANT_HIT_DOWN_WIDTH = GIANT_HIT_UP_ALL_WIDTH / GIANT_HIT_AMOUNT;
const int GIANT_HIT_DOWN_HEIGHT = 153;
const int GIANT_HIT_DOWN_END_X = 1372;

//hit right details :
const int GIANT_HIT_RIGHT_START_X = 0;
const int GIANT_HIT_RIGHT_START_Y = 662;
const int GIANT_HIT_RIGHT_ALL_WIDTH = 1563;
const int GIANT_HIT_RIGHT_WIDTH = (GIANT_HIT_RIGHT_ALL_WIDTH / GIANT_HIT_AMOUNT) + 8;
const int GIANT_HIT_RIGHT_HEIGHT = 125;
const int GIANT_HIT_RIGHT_END_X = 1421;

//hit up - right details :
const int GIANT_HIT_UP_RIGHT_START_X = 0;
const int GIANT_HIT_UP_RIGHT_START_Y = 853;
const int GIANT_HIT_UP_RIGHT_ALL_WIDTH = 1610;
const int GIANT_HIT_UP_RIGHT_WIDTH = (GIANT_HIT_UP_RIGHT_ALL_WIDTH / GIANT_HIT_AMOUNT);
const int GIANT_HIT_UP_RIGHT_HEIGHT = 138;
const int GIANT_HIT_UP_RIGHT_END_X = 1407;

//walk down details :
const int GIANT_WALK_DOWN_START_X = 0;
const int GIANT_WALK_DOWN_START_Y = 1076;
const int GIANT_WALK_DOWN_ALL_WIDTH = 1496;
const int GIANT_WALK_DOWN_WIDTH = (GIANT_WALK_DOWN_ALL_WIDTH / GIANT_WALK_AMOUNT);
const int GIANT_WALK_DOWN_HEIGHT = 115;
const int GIANT_WALK_DOWN_END_X = 1309;

//walk right details :
const int GIANT_WALK_RIGHT_START_X = 0;
const int GIANT_WALK_RIGHT_START_Y = 1278;
const int GIANT_WALK_RIGHT_ALL_WIDTH = 1582;
const int GIANT_WALK_RIGHT_WIDTH = (GIANT_WALK_RIGHT_ALL_WIDTH / GIANT_WALK_AMOUNT);
const int GIANT_WALK_RIGHT_HEIGHT = 124;
const int GIANT_WALK_RIGHT_END_X = 1379;

//walk up - right details :
const int GIANT_WALK_UP_RIGHT_START_X = 0;
const int GIANT_WALK_UP_RIGHT_START_Y = 1490;
const int GIANT_WALK_UP_RIGHT_ALL_WIDTH = 1575;
const int GIANT_WALK_UP_RIGHT_WIDTH = (GIANT_WALK_UP_RIGHT_ALL_WIDTH / GIANT_WALK_AMOUNT);
const int GIANT_WALK_UP_RIGHT_HEIGHT = 116;
const int GIANT_WALK_UP_RIGHT_END_X = 1372;

//walk down - right details :
const int GIANT_WALK_DOWN_RIGHT_START_X = 0;
const int GIANT_WALK_DOWN_RIGHT_START_Y = 1686;
const int GIANT_WALK_DOWN_RIGHT_ALL_WIDTH = 1576;
const int GIANT_WALK_DOWN_RIGHT_WIDTH = (GIANT_WALK_DOWN_RIGHT_ALL_WIDTH / GIANT_WALK_AMOUNT);
const int GIANT_WALK_DOWN_RIGHT_HEIGHT = 117;
const int GIANT_WALK_DOWN_RIGHT_END_X = 1379;

//walk up details :
const int GIANT_WALK_UP_START_X = 0;
const int GIANT_WALK_UP_START_Y = 1902;
const int GIANT_WALK_UP_ALL_WIDTH = 1587;
const int GIANT_WALK_UP_WIDTH = (GIANT_WALK_UP_ALL_WIDTH / GIANT_WALK_AMOUNT);
const int GIANT_WALK_UP_HEIGHT = 104;
const int GIANT_WALK_UP_END_X = 1386;


// ************************** Knight consts **************************
const int KNIGHT_HIT_AMOUNT = 14;
const int KNIGHT_WALK_AMOUNT = 12;

const int KNIGHT_HIT_DOWN_START_X = 0;
const int KNIGHT_HIT_DOWN_START_Y = 0;
const int KNIGHT_HIT_DOWN_ALL_WIDTH = 2616;
const int KNIGHT_HIT_DOWN_WIDTH = KNIGHT_HIT_DOWN_ALL_WIDTH / KNIGHT_HIT_AMOUNT;
const int KNIGHT_HIT_DOWN_HEIGHT = 182;
const int KNIGHT_HIT_DOWN_END_X = 2379;

const int KNIGHT_HIT_RIGHT_START_X = 0;
const int KNIGHT_HIT_RIGHT_START_Y = 205;
const int KNIGHT_HIT_RIGHT_ALL_WIDTH = 2617;
const int KNIGHT_HIT_RIGHT_WIDTH = (KNIGHT_HIT_RIGHT_ALL_WIDTH / KNIGHT_HIT_AMOUNT);
const int KNIGHT_HIT_RIGHT_HEIGHT = 132;
const int KNIGHT_HIT_RIGHT_END_X = 2418;

const int KNIGHT_HIT_UP_RIGHT_START_X = 14;
const int KNIGHT_HIT_UP_RIGHT_START_Y = 376;
const int KNIGHT_HIT_UP_RIGHT_ALL_WIDTH = 2603;
const int KNIGHT_HIT_UP_RIGHT_WIDTH = (KNIGHT_HIT_UP_RIGHT_ALL_WIDTH / KNIGHT_HIT_AMOUNT);
const int KNIGHT_HIT_UP_RIGHT_HEIGHT = 141;
const int KNIGHT_HIT_UP_RIGHT_END_X = 2419;

const int KNIGHT_HIT_DOWN_RIGHT_START_X = -5;
const int KNIGHT_HIT_DOWN_RIGHT_START_Y = 547;
const int KNIGHT_HIT_DOWN_RIGHT_ALL_WIDTH = 2600;
const int KNIGHT_HIT_DOWN_RIGHT_WIDTH = KNIGHT_HIT_DOWN_RIGHT_ALL_WIDTH / KNIGHT_HIT_AMOUNT;
const int KNIGHT_HIT_DOWN_RIGHT_HEIGHT = 168;
const int KNIGHT_HIT_DOWN_RIGHT_END_X = 2379;

const int KNIGHT_HIT_UP_START_X = 0;
const int KNIGHT_HIT_UP_START_Y = 720;
const int KNIGHT_HIT_UP_ALL_WIDTH = 2632;
const int KNIGHT_HIT_UP_WIDTH = KNIGHT_HIT_UP_ALL_WIDTH / KNIGHT_HIT_AMOUNT;
const int KNIGHT_HIT_UP_HEIGHT = 150;
const int KNIGHT_HIT_UP_END_X = 2405;

const int KNIGHT_WALK_DOWN_RIGHT_START_X = 0;
const int KNIGHT_WALK_DOWN_RIGHT_START_Y = 952;
const int KNIGHT_WALK_DOWN_RIGHT_ALL_WIDTH = 2260;
const int KNIGHT_WALK_DOWN_RIGHT_WIDTH = (KNIGHT_WALK_DOWN_RIGHT_ALL_WIDTH / KNIGHT_WALK_AMOUNT);
const int KNIGHT_WALK_DOWN_RIGHT_HEIGHT = 104;
const int KNIGHT_WALK_DOWN_RIGHT_END_X = 2035;

const int KNIGHT_WALK_UP_START_X = 0;
const int KNIGHT_WALK_UP_START_Y = 1119;
const int KNIGHT_WALK_UP_ALL_WIDTH = 2232;
const int KNIGHT_WALK_UP_WIDTH = (KNIGHT_WALK_UP_ALL_WIDTH / KNIGHT_WALK_AMOUNT);
const int KNIGHT_WALK_UP_HEIGHT = 143;
const int KNIGHT_WALK_UP_END_X = 2013;

const int KNIGHT_WALK_DOWN_START_X = 0;
const int KNIGHT_WALK_DOWN_START_Y = 1320;
const int KNIGHT_WALK_DOWN_ALL_WIDTH = 2246;
const int KNIGHT_WALK_DOWN_WIDTH = (KNIGHT_WALK_DOWN_ALL_WIDTH / KNIGHT_WALK_AMOUNT);
const int KNIGHT_WALK_DOWN_HEIGHT = 97;
const int KNIGHT_WALK_DOWN_END_X = 2024;

const int KNIGHT_WALK_RIGHT_START_X = 0;
const int KNIGHT_WALK_RIGHT_START_Y = 1460;
const int KNIGHT_WALK_RIGHT_ALL_WIDTH = 2248;
const int KNIGHT_WALK_RIGHT_WIDTH = (KNIGHT_WALK_RIGHT_ALL_WIDTH / KNIGHT_WALK_AMOUNT);
const int KNIGHT_WALK_RIGHT_HEIGHT = 145;
const int KNIGHT_WALK_RIGHT_END_X = 2024;

const int KNIGHT_WALK_UP_RIGHT_START_X = 0;
const int KNIGHT_WALK_UP_RIGHT_START_Y = 1641;
const int KNIGHT_WALK_UP_RIGHT_ALL_WIDTH = 2250;
const int KNIGHT_WALK_UP_RIGHT_WIDTH = (KNIGHT_WALK_UP_RIGHT_ALL_WIDTH / KNIGHT_WALK_AMOUNT);
const int KNIGHT_WALK_UP_RIGHT_HEIGHT = 143;
const int KNIGHT_WALK_UP_RIGHT_END_X = 2013;


// ************************** Minions consts **************************
const int MINIONS_HIT_AMOUNT = 7;
const int MINIONS_WALK_AMOUNT = 8;

const int MINIONS_HIT_DOWN_START_X = 0;
const int MINIONS_HIT_DOWN_START_Y = 0;
const int MINIONS_HIT_DOWN_ALL_WIDTH = 1205;
const int MINIONS_HIT_DOWN_WIDTH = MINIONS_HIT_DOWN_ALL_WIDTH / MINIONS_HIT_AMOUNT;
const int MINIONS_HIT_DOWN_HEIGHT = 159;
const int MINIONS_HIT_DOWN_END_X = 1032;

const int MINIONS_HIT_RIGHT_START_X = 15;
const int MINIONS_HIT_RIGHT_START_Y = 164;
const int MINIONS_HIT_RIGHT_ALL_WIDTH = 1211;
const int MINIONS_HIT_RIGHT_WIDTH = (MINIONS_HIT_RIGHT_ALL_WIDTH / MINIONS_HIT_AMOUNT);
const int MINIONS_HIT_RIGHT_HEIGHT = 145;
const int MINIONS_HIT_RIGHT_END_X = 1053;

const int MINIONS_HIT_UP_RIGHT_START_X = 11;
const int MINIONS_HIT_UP_RIGHT_START_Y = 320;
const int MINIONS_HIT_UP_RIGHT_ALL_WIDTH = 1197;
const int MINIONS_HIT_UP_RIGHT_WIDTH = (MINIONS_HIT_UP_RIGHT_ALL_WIDTH / MINIONS_HIT_AMOUNT);
const int MINIONS_HIT_UP_RIGHT_HEIGHT = 149;
const int MINIONS_HIT_UP_RIGHT_END_X = 1037;

const int MINIONS_HIT_DOWN_RIGHT_START_X = 10;
const int MINIONS_HIT_DOWN_RIGHT_START_Y = 489;
const int MINIONS_HIT_DOWN_RIGHT_ALL_WIDTH = 1198;
const int MINIONS_HIT_DOWN_RIGHT_WIDTH = MINIONS_HIT_DOWN_RIGHT_ALL_WIDTH / MINIONS_HIT_AMOUNT;
const int MINIONS_HIT_DOWN_RIGHT_HEIGHT = 138;
const int MINIONS_HIT_DOWN_RIGHT_END_X = 1018;

const int MINIONS_HIT_UP_START_X = 0;
const int MINIONS_HIT_UP_START_Y = 641;
const int MINIONS_HIT_UP_ALL_WIDTH = 1195;
const int MINIONS_HIT_UP_WIDTH = MINIONS_HIT_UP_ALL_WIDTH / MINIONS_HIT_AMOUNT;
const int MINIONS_HIT_UP_HEIGHT = 125;
const int MINIONS_HIT_UP_END_X = 1020;

const int MINIONS_WALK_DOWN_RIGHT_START_X = 0;
const int MINIONS_WALK_DOWN_RIGHT_START_Y = 796;
const int MINIONS_WALK_DOWN_RIGHT_ALL_WIDTH = 1376;
const int MINIONS_WALK_DOWN_RIGHT_WIDTH = (MINIONS_WALK_DOWN_RIGHT_ALL_WIDTH / MINIONS_WALK_AMOUNT);
const int MINIONS_WALK_DOWN_RIGHT_HEIGHT = 141;
const int MINIONS_WALK_DOWN_RIGHT_END_X = 1214;

const int MINIONS_WALK_UP_START_X = 10;
const int MINIONS_WALK_UP_START_Y = 964;
const int MINIONS_WALK_UP_ALL_WIDTH = 1376;
const int MINIONS_WALK_UP_WIDTH = (MINIONS_WALK_UP_ALL_WIDTH / MINIONS_WALK_AMOUNT);
const int MINIONS_WALK_UP_HEIGHT = 114;
const int MINIONS_WALK_UP_END_X = 1214;

const int MINIONS_WALK_DOWN_START_X = 0;
const int MINIONS_WALK_DOWN_START_Y = 1140;
const int MINIONS_WALK_DOWN_ALL_WIDTH = 1376;
const int MINIONS_WALK_DOWN_WIDTH = (MINIONS_WALK_DOWN_ALL_WIDTH / MINIONS_WALK_AMOUNT);
const int MINIONS_WALK_DOWN_HEIGHT = 110;
const int MINIONS_WALK_DOWN_END_X = 1204;

const int MINIONS_WALK_RIGHT_START_X = 0;
const int MINIONS_WALK_RIGHT_START_Y = 1273;
const int MINIONS_WALK_RIGHT_ALL_WIDTH = 1376;
const int MINIONS_WALK_RIGHT_WIDTH = (MINIONS_WALK_RIGHT_ALL_WIDTH / MINIONS_WALK_AMOUNT);
const int MINIONS_WALK_RIGHT_HEIGHT = 131;
const int MINIONS_WALK_RIGHT_END_X = 1204;

const int MINIONS_WALK_UP_RIGHT_START_X = 0;
const int MINIONS_WALK_UP_RIGHT_START_Y = 1437;
const int MINIONS_WALK_UP_RIGHT_ALL_WIDTH = 1376;
const int MINIONS_WALK_UP_RIGHT_WIDTH = (MINIONS_WALK_UP_RIGHT_ALL_WIDTH / MINIONS_WALK_AMOUNT);
const int MINIONS_WALK_UP_RIGHT_HEIGHT = 124;
const int MINIONS_WALK_UP_RIGHT_END_X = 1204;


// ************************** valkyrie consts **************************
const int VALKYRIE_HIT_AMOUNT = 12;
const int VALKYRIE_WALK_AMOUNT = 8;

const int VALKYRIE_HIT_DOWN_START_X = 0;
const int VALKYRIE_HIT_DOWN_START_Y = 18;
const int VALKYRIE_HIT_DOWN_ALL_WIDTH = 2074;
const int VALKYRIE_HIT_DOWN_WIDTH = VALKYRIE_HIT_DOWN_ALL_WIDTH / VALKYRIE_HIT_AMOUNT;
const int VALKYRIE_HIT_DOWN_HEIGHT = 135;
const int VALKYRIE_HIT_DOWN_END_X = 1892;

const int VALKYRIE_HIT_RIGHT_START_X = 0;
const int VALKYRIE_HIT_RIGHT_START_Y = 161;
const int VALKYRIE_HIT_RIGHT_ALL_WIDTH = 2075;
const int VALKYRIE_HIT_RIGHT_WIDTH = VALKYRIE_HIT_DOWN_ALL_WIDTH / VALKYRIE_HIT_AMOUNT;
const int VALKYRIE_HIT_RIGHT_HEIGHT = 124;
const int VALKYRIE_HIT_RIGHT_END_X = 1892;

const int VALKYRIE_HIT_UP_RIGHT_START_X = 0;
const int VALKYRIE_HIT_UP_RIGHT_START_Y = 305;
const int VALKYRIE_HIT_UP_RIGHT_ALL_WIDTH = 2055;
const int VALKYRIE_HIT_UP_RIGHT_WIDTH = VALKYRIE_HIT_DOWN_ALL_WIDTH / VALKYRIE_HIT_AMOUNT;
const int VALKYRIE_HIT_UP_RIGHT_HEIGHT = 132;
const int VALKYRIE_HIT_UP_RIGHT_END_X = 1892;

const int VALKYRIE_HIT_DOWN_RIGHT_START_X = 0;
const int VALKYRIE_HIT_DOWN_RIGHT_START_Y = 470;
const int VALKYRIE_HIT_DOWN_RIGHT_ALL_WIDTH = 2075;
const int VALKYRIE_HIT_DOWN_RIGHT_WIDTH = VALKYRIE_HIT_DOWN_ALL_WIDTH / VALKYRIE_HIT_AMOUNT;
const int VALKYRIE_HIT_DOWN_RIGHT_HEIGHT = 124;
const int VALKYRIE_HIT_DOWN_RIGHT_END_X = 1892;

const int VALKYRIE_HIT_UP_START_X = -10;
const int VALKYRIE_HIT_UP_START_Y = 611;
const int VALKYRIE_HIT_UP_ALL_WIDTH = 2045;
const int VALKYRIE_HIT_UP_WIDTH = VALKYRIE_HIT_DOWN_ALL_WIDTH / VALKYRIE_HIT_AMOUNT;
const int VALKYRIE_HIT_UP_HEIGHT = 131;
const int VALKYRIE_HIT_UP_END_X = 1882;

const int VALKYRIE_WALK_DOWN_RIGHT_START_X = 0;
const int VALKYRIE_WALK_DOWN_RIGHT_START_Y = 800;
const int VALKYRIE_WALK_DOWN_RIGHT_ALL_WIDTH = 1383;
const int VALKYRIE_WALK_DOWN_RIGHT_WIDTH = VALKYRIE_WALK_DOWN_RIGHT_ALL_WIDTH / VALKYRIE_WALK_AMOUNT;
const int VALKYRIE_WALK_DOWN_RIGHT_HEIGHT = 80;
const int VALKYRIE_WALK_DOWN_RIGHT_END_X = 1183;

const int VALKYRIE_WALK_UP_RIGHT_START_X = 0;
const int VALKYRIE_WALK_UP_RIGHT_START_Y = 950;
const int VALKYRIE_WALK_UP_RIGHT_ALL_WIDTH = 1376;
const int VALKYRIE_WALK_UP_RIGHT_WIDTH = VALKYRIE_WALK_UP_RIGHT_ALL_WIDTH / VALKYRIE_WALK_AMOUNT;
const int VALKYRIE_WALK_UP_RIGHT_HEIGHT = 82;
const int VALKYRIE_WALK_UP_RIGHT_END_X = 1183;

const int VALKYRIE_WALK_DOWN_START_X = 0;
const int VALKYRIE_WALK_DOWN_START_Y = 1108;
const int VALKYRIE_WALK_DOWN_ALL_WIDTH = 1387;
const int VALKYRIE_WALK_DOWN_WIDTH = VALKYRIE_WALK_DOWN_ALL_WIDTH / VALKYRIE_WALK_AMOUNT;
const int VALKYRIE_WALK_DOWN_HEIGHT = 78;
const int VALKYRIE_WALK_DOWN_END_X = 1190;

const int VALKYRIE_WALK_RIGHT_START_X = 0;
const int VALKYRIE_WALK_RIGHT_START_Y = 1253;
const int VALKYRIE_WALK_RIGHT_ALL_WIDTH = 1378;
const int VALKYRIE_WALK_RIGHT_WIDTH = VALKYRIE_WALK_RIGHT_ALL_WIDTH / VALKYRIE_WALK_AMOUNT;
const int VALKYRIE_WALK_RIGHT_HEIGHT = 79;
const int VALKYRIE_WALK_RIGHT_END_X = 1183;

const int VALKYRIE_WALK_UP_START_X = -10;
const int VALKYRIE_WALK_UP_START_Y = 1413;
const int VALKYRIE_WALK_UP_ALL_WIDTH = 1394;
const int VALKYRIE_WALK_UP_WIDTH = VALKYRIE_WALK_UP_ALL_WIDTH / VALKYRIE_WALK_AMOUNT;
const int VALKYRIE_WALK_UP_HEIGHT = 73;
const int VALKYRIE_WALK_UP_END_X = 1187;


// ************************** pekka consts **************************
const int PEKKA_HIT_AMOUNT = 7;
const int PEKKA_WALK_AMOUNT = 10;

const int PEKKA_HIT_DOWN_START_X = -10;
const int PEKKA_HIT_DOWN_START_Y = 11;
const int PEKKA_HIT_DOWN_ALL_WIDTH = 1714;
const int PEKKA_HIT_DOWN_WIDTH = 230;
const int PEKKA_HIT_DOWN_HEIGHT = 213;
const int PEKKA_HIT_DOWN_END_X = 1370;

const int PEKKA_HIT_RIGHT_START_X = 0;
const int PEKKA_HIT_RIGHT_START_Y = 273;
const int PEKKA_HIT_RIGHT_ALL_WIDTH = 1624;
const int PEKKA_HIT_RIGHT_WIDTH = 230;
const int PEKKA_HIT_RIGHT_HEIGHT = 161;
const int PEKKA_HIT_RIGHT_END_X = 1380;

const int PEKKA_HIT_UP_RIGHT_START_X = 0;
const int PEKKA_HIT_UP_RIGHT_START_Y = 505;
const int PEKKA_HIT_UP_RIGHT_ALL_WIDTH = 1667;
const int PEKKA_HIT_UP_RIGHT_WIDTH = 238;
const int PEKKA_HIT_UP_RIGHT_HEIGHT = 141;
const int PEKKA_HIT_UP_RIGHT_END_X = 1428;

const int PEKKA_HIT_DOWN_RIGHT_START_X = -10;
const int PEKKA_HIT_DOWN_RIGHT_START_Y = 715;
const int PEKKA_HIT_DOWN_RIGHT_ALL_WIDTH = 1590;
const int PEKKA_HIT_DOWN_RIGHT_WIDTH = 227;
const int PEKKA_HIT_DOWN_RIGHT_HEIGHT = 186;
const int PEKKA_HIT_DOWN_RIGHT_END_X = 1352;

const int PEKKA_HIT_UP_START_X = 0;
const int PEKKA_HIT_UP_START_Y = 940;
const int PEKKA_HIT_UP_ALL_WIDTH = 1644;
const int PEKKA_HIT_UP_WIDTH = 235;
const int PEKKA_HIT_UP_HEIGHT = 150;
const int PEKKA_HIT_UP_END_X = 1410;

const int PEKKA_WALK_DOWN_RIGHT_START_X = 0;
const int PEKKA_WALK_DOWN_RIGHT_START_Y = 1220;
const int PEKKA_WALK_DOWN_RIGHT_ALL_WIDTH = 2329;
const int PEKKA_WALK_DOWN_RIGHT_WIDTH = 230;
const int PEKKA_WALK_DOWN_RIGHT_HEIGHT = 130;
const int PEKKA_WALK_DOWN_RIGHT_END_X = 2070;

const int PEKKA_WALK_UP_START_X = 0;
const int PEKKA_WALK_UP_START_Y = 1433;
const int PEKKA_WALK_UP_ALL_WIDTH = 2309;
const int PEKKA_WALK_UP_WIDTH = PEKKA_WALK_UP_ALL_WIDTH / PEKKA_WALK_AMOUNT;
const int PEKKA_WALK_UP_HEIGHT = 127;
const int PEKKA_WALK_UP_END_X = 2070;

const int PEKKA_WALK_DOWN_START_X = 0;
const int PEKKA_WALK_DOWN_START_Y = 1668;
const int PEKKA_WALK_DOWN_ALL_WIDTH = 2324;
const int PEKKA_WALK_DOWN_WIDTH = 228;
const int PEKKA_WALK_DOWN_HEIGHT = 128;
const int PEKKA_WALK_DOWN_END_X = 2052;

const int PEKKA_WALK_RIGHT_START_X = 0;
const int PEKKA_WALK_RIGHT_START_Y = 1890;
const int PEKKA_WALK_RIGHT_ALL_WIDTH = 2339;
const int PEKKA_WALK_RIGHT_WIDTH = 230;
const int PEKKA_WALK_RIGHT_HEIGHT = 140;
const int PEKKA_WALK_RIGHT_END_X = 2070;

const int PEKKA_WALK_UP_RIGHT_START_X = 0;
const int PEKKA_WALK_UP_RIGHT_START_Y = 2129;
const int PEKKA_WALK_UP_RIGHT_ALL_WIDTH = 2324;
const int PEKKA_WALK_UP_RIGHT_WIDTH = 230;
const int PEKKA_WALK_UP_RIGHT_HEIGHT = 122;
const int PEKKA_WALK_UP_RIGHT_END_X = 1840;


// ************************** Dart Goblin **************************
const int DART_GOBLIN_HIT_AMOUNT = 5;
const int DART_GOBLIN_WALK_AMOUNT = 8;

const int DART_GOBLIN_HIT_DOWN_START_X = 0;
const int DART_GOBLIN_HIT_DOWN_START_Y = 6;
const int DART_GOBLIN_HIT_DOWN_ALL_WIDTH = 618;
const int DART_GOBLIN_HIT_DOWN_WIDTH = DART_GOBLIN_HIT_DOWN_ALL_WIDTH / DART_GOBLIN_HIT_AMOUNT;
const int DART_GOBLIN_HIT_DOWN_HEIGHT = 134;
const int DART_GOBLIN_HIT_DOWN_END_X = 492;

const int DART_GOBLIN_HIT_RIGHT_START_X = 0;
const int DART_GOBLIN_HIT_RIGHT_START_Y = 161;
const int DART_GOBLIN_HIT_RIGHT_ALL_WIDTH = 676;
const int DART_GOBLIN_HIT_RIGHT_WIDTH = (DART_GOBLIN_HIT_RIGHT_ALL_WIDTH / DART_GOBLIN_HIT_AMOUNT);
const int DART_GOBLIN_HIT_RIGHT_HEIGHT = 93;
const int DART_GOBLIN_HIT_RIGHT_END_X = 540;

const int DART_GOBLIN_HIT_UP_RIGHT_START_X = 0;
const int DART_GOBLIN_HIT_UP_RIGHT_START_Y = 297;
const int DART_GOBLIN_HIT_UP_RIGHT_ALL_WIDTH = 666;
const int DART_GOBLIN_HIT_UP_RIGHT_WIDTH = (DART_GOBLIN_HIT_UP_RIGHT_ALL_WIDTH / DART_GOBLIN_HIT_AMOUNT);
const int DART_GOBLIN_HIT_UP_RIGHT_HEIGHT = 94;
const int DART_GOBLIN_HIT_UP_RIGHT_END_X = 532;

const int DART_GOBLIN_HIT_DOWN_RIGHT_START_X = 0;
const int DART_GOBLIN_HIT_DOWN_RIGHT_START_Y = 428;
const int DART_GOBLIN_HIT_DOWN_RIGHT_ALL_WIDTH = 652;
const int DART_GOBLIN_HIT_DOWN_RIGHT_WIDTH = DART_GOBLIN_HIT_DOWN_RIGHT_ALL_WIDTH / DART_GOBLIN_HIT_AMOUNT;
const int DART_GOBLIN_HIT_DOWN_RIGHT_HEIGHT = 122;
const int DART_GOBLIN_HIT_DOWN_RIGHT_END_X = 520;

const int DART_GOBLIN_HIT_UP_START_X = 0;
const int DART_GOBLIN_HIT_UP_START_Y = 564;
const int DART_GOBLIN_HIT_UP_ALL_WIDTH = 655;
const int DART_GOBLIN_HIT_UP_WIDTH = DART_GOBLIN_HIT_UP_ALL_WIDTH / DART_GOBLIN_HIT_AMOUNT;
const int DART_GOBLIN_HIT_UP_HEIGHT = 107;
const int DART_GOBLIN_HIT_UP_END_X = 524;

const int DART_GOBLIN_WALK_DOWN_RIGHT_START_X = 0;
const int DART_GOBLIN_WALK_DOWN_RIGHT_START_Y = 705;
const int DART_GOBLIN_WALK_DOWN_RIGHT_ALL_WIDTH = 1040;
const int DART_GOBLIN_WALK_DOWN_RIGHT_WIDTH = (DART_GOBLIN_WALK_DOWN_RIGHT_ALL_WIDTH / DART_GOBLIN_WALK_AMOUNT);
const int DART_GOBLIN_WALK_DOWN_RIGHT_HEIGHT = 111;
const int DART_GOBLIN_WALK_DOWN_RIGHT_END_X = 910;

const int DART_GOBLIN_WALK_UP_START_X = 0;
const int DART_GOBLIN_WALK_UP_START_Y = 877;
const int DART_GOBLIN_WALK_UP_ALL_WIDTH = 1030;
const int DART_GOBLIN_WALK_UP_WIDTH = (DART_GOBLIN_WALK_UP_ALL_WIDTH / DART_GOBLIN_WALK_AMOUNT);
const int DART_GOBLIN_WALK_UP_HEIGHT = 83;
const int DART_GOBLIN_WALK_UP_END_X = 889;

const int DART_GOBLIN_WALK_DOWN_START_X = 0;
const int DART_GOBLIN_WALK_DOWN_START_Y = 989;
const int DART_GOBLIN_WALK_DOWN_ALL_WIDTH = 1031;
const int DART_GOBLIN_WALK_DOWN_WIDTH = (DART_GOBLIN_WALK_DOWN_ALL_WIDTH / DART_GOBLIN_WALK_AMOUNT);
const int DART_GOBLIN_WALK_DOWN_HEIGHT = 105;
const int DART_GOBLIN_WALK_DOWN_END_X = 882;

const int DART_GOBLIN_WALK_RIGHT_START_X = 0;
const int DART_GOBLIN_WALK_RIGHT_START_Y = 1140;
const int DART_GOBLIN_WALK_RIGHT_ALL_WIDTH = 1016;
const int DART_GOBLIN_WALK_RIGHT_WIDTH = (DART_GOBLIN_WALK_RIGHT_ALL_WIDTH / DART_GOBLIN_WALK_AMOUNT);
const int DART_GOBLIN_WALK_RIGHT_HEIGHT = 107;
const int DART_GOBLIN_WALK_RIGHT_END_X = 889;

const int DART_GOBLIN_WALK_UP_RIGHT_START_X = 0;
const int DART_GOBLIN_WALK_UP_RIGHT_START_Y = 1297;
const int DART_GOBLIN_WALK_UP_RIGHT_ALL_WIDTH = 1034;
const int DART_GOBLIN_WALK_UP_RIGHT_WIDTH = (DART_GOBLIN_WALK_UP_RIGHT_ALL_WIDTH / DART_GOBLIN_WALK_AMOUNT);
const int DART_GOBLIN_WALK_UP_RIGHT_HEIGHT = 88;
const int DART_GOBLIN_WALK_UP_RIGHT_END_X = 882;


// ************************** Fireball consts **************************
const int FIREBALL_FLY_AMOUNT = 36;
const int FIREBALL_EXPLOSION_AMOUNT = 7;

//flying details :

const int FIREBALL_FLY_START_X = 0;
const int FIREBALL_FLY_START_Y = 158;
const int FIREBALL_FLY_ALL_WIDTH = 1440;
const int FIREBALL_FLY_WIDTH = FIREBALL_FLY_ALL_WIDTH / FIREBALL_FLY_AMOUNT;
const int FIREBALL_FLY_HEIGHT = 57;
const int FIREBALL_FLY_END_X = 1360;

const int FIREBALL_EXPLOSION_START_X = 0;
const int FIREBALL_EXPLOSION_START_Y = 0;
const int FIREBALL_EXPLOSION_ALL_WIDTH = 1092;
const int FIREBALL_EXPLOSION_WIDTH = (FIREBALL_EXPLOSION_ALL_WIDTH / FIREBALL_EXPLOSION_AMOUNT); // 156
const int FIREBALL_EXPLOSION_HEIGHT = 154;

const int FIREBALL_EXPLOSION_END_X = 1092;




// ************************** Arrows consts **************************
//flying details :

const int ARROWS_FLY_RIGHT_START_X = 0;
const int ARROWS_FLY_RIGHT_START_Y = 0;
const int ARROWS_FLY_RIGHT_WIDTH = 170;
const int ARROWS_FLY_RIGHT_HEIGHT = 115;

const int ARROWS_FLY_UP_START_X = 0;
const int ARROWS_FLY_UP_START_Y = 125;
const int ARROWS_FLY_UP_WIDTH = 131;
const int ARROWS_FLY_UP_HEIGHT = 179;

const int ARROWS_FLY_LEFT_START_X = 0;
const int ARROWS_FLY_LEFT_START_Y = 334;
const int ARROWS_FLY_LEFT_WIDTH = 168;
const int ARROWS_FLY_LEFT_HEIGHT = 120;

const int ARROWS_FLY_DOWN_START_X = 0;
const int ARROWS_FLY_DOWN_START_Y = 459;
const int ARROWS_FLY_DOWN_WIDTH = 132;
const int ARROWS_FLY_DOWN_HEIGHT = 187;

const int ARROWS_FLY_DOWN_LEFT_START_X = 0;
const int ARROWS_FLY_DOWN_LEFT_START_Y = 660;
const int ARROWS_FLY_DOWN_LEFT_WIDTH = 173;
const int ARROWS_FLY_DOWN_LEFT_HEIGHT = 177;

const int ARROWS_FLY_UP_LEFT_START_X = 0;
const int ARROWS_FLY_UP_LEFT_START_Y = 865;
const int ARROWS_FLY_UP_LEFT_WIDTH = 171;
const int ARROWS_FLY_UP_LEFT_HEIGHT = 177;

const int ARROWS_FLY_UP_RIGHT_START_X = 0;
const int ARROWS_FLY_UP_RIGHT_START_Y = 1064;
const int ARROWS_FLY_UP_RIGHT_WIDTH = 173;
const int ARROWS_FLY_UP_RIGHT_HEIGHT = 176;

const int ARROWS_FLY_DOWN_RIGHT_START_X = 0;
const int ARROWS_FLY_DOWN_RIGHT_START_Y = 1259;
const int ARROWS_FLY_DOWN_RIGHT_WIDTH = 171;
const int ARROWS_FLY_DOWN_RIGHT_HEIGHT = 178;

// smoke details:
const int ARROWS_SMOKE_AMOUNT = 9;

const int ARROWS_SMOKE_START_X = 0;
const int ARROWS_SMOKE_START_Y = 0;
const int ARROWS_SMOKE_ALL_WIDTH = 1629;
const int ARROWS_SMOKE_WIDTH = (ARROWS_SMOKE_ALL_WIDTH / ARROWS_SMOKE_AMOUNT);
const int ARROWS_SMOKE_HEIGHT = 159;

const int ARROWS_SMOKE_END_X = 1448;








